### ISSUE TITLE
Classes declared with Ember.Object.extend have signature "(unknown mixin)"

### ISSUE THREAD

**Issue by taras** [stefanpenner/ember-app-kit#124]
This is happening on the master branch. The screenshot shows how to reproduce it.

![screen shot 2013-09-07 at 11 11 06](https://f.cloud.github.com/assets/74687/1101568/4b7ac550-17d2-11e3-9f03-9664d7706b41.png)

It might be related to #87.

**Comment by lolmaus** [comment]
Ran into this issue today. Was confused.
