### ISSUE TITLE
How to reference Views in Handlebars helper?

### ISSUE THREAD

**Issue by jayphelps** [stefanpenner/ember-app-kit#74]
I can't seem to do a very common use case for my Ember apps:

``` handlebars
{{view App.SomeView}}
```

I don't see any app kit code added to resolve these, and the AMD modules aren't appended to the application namespace obviously. My best guess is that this just isn't something appkit supports yet?

Even though I didn't think they'd work, I also tried:

``` handlebars
{{view some}}
{{view SomeView}}
{{view views/SomeView}}
{{view app/views/SomeView}}
{{view appkit/views/SomeView}}
{{view appkit.views.SomeView}}
```

**Comment by Nininea-zz** [comment]
I have the same problem, but only in internet explorer
http://stackoverflow.com/questions/36029620/ember-unable-to-find-view-in-internet-explorer

here are versions i use:
version: 0.0.40
node: 0.12.0
npm: 1.4.29

view helper in template: 
{view "wizard-menu" activeIndex=0 parameter=0}}
